id: I5BF19146
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:43:12+00:00'
last_modified: '2022-06-07T15:10:10.279545+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17344
  title: གསང་བ་འདུས་པའི་མདུན་བསྐྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C33C:
      image_group_id: I8LS17351
      title: ''
      total_pages: 150
      order: 1
      base_file: C33C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
